
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LogicaPersistencia
{

using System;
    using System.Collections.Generic;
    
public partial class Moneda
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Moneda()
    {

        this.Carrito = new HashSet<Carrito>();

    }


    public int MonedaId { get; set; }

    public string MonedaAbreviatura { get; set; }

    public string MonedaDescripción { get; set; }

    public decimal MonedaCotizacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Carrito> Carrito { get; set; }

}

}
