//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaPersistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string TipoUsuario { get; set; }
        public string UsuarioEmail { get; set; }
        public string UsuarioContrasenia { get; set; }
        public bool UsuarioActivo { get; set; }
    
        public virtual BackOffice BackOffice { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
